export const CREATING_DRAGON = 'CREATING_DRAGON'
export const CREATED_DRAGON = 'CREATED_DRAGON'

export const SAVING_DRAGON = 'SAVING_DRAGON'
export const SAVED_DRAGON = 'SAVED_DRAGON'

export const DELETING_DRAGON = 'DELETING_DRAGON'
export const DELETED_DRAGON = 'DELETED_DRAGON'

export const FETCHING_DRAGON = 'FETCHING_DRAGON'
export const FETCH_DRAGON = 'FETCH_DRAGON'

export const FETCHING_DRAGON_LIST = 'FETCHING_DRAGON_LIST'
export const FETCH_DRAGON_LIST = 'FETCH_DRAGON_LIST'

export const LOGIN = 'LOGIN'
export const LOGOUT = 'LOGOUT'

export const LOADER = 'LOADER'
